### ISSUE TITLE
学習用・テスト用データの件数

### ISSUE THREAD

**Issue by mayu-ot** [tomomiyazaki/alcon2017prmu#1]
学習用・テスト用データが全体に対して少ないのですが，開発に使えるのはこれだけでしょうか．

target_lv1.csv: 49K
target_lv1_samp_0.9.csv: 4K
target_lv1_test_0.1.csv: 424

**Comment by yasutomo57jp** [comment]
更新されたようです．
新しいバージョンでは，
target_lv1_train_0.9.csv: 44K
target_lv1_test_1.csv: 46
となっています．

**Comment by mayu-ot** [comment]
そうでしたか．ありがとうございます．
